version: "3.6"

services:
  YOUR-APP-NAME-api-db:
    image: postgres:12
    container_name: YOUR-APP-NAME-api-db
    restart: always
    env_file: .env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data:rw
    networks:
      - YOUR-APP-NAME

  YOUR-APP-NAME-api-redis:
    image: redis
    container_name: YOUR-APP-NAME-api-redis
    restart: always
    volumes:
      - ./data/redis:/data:rw
    networks:
      - YOUR-APP-NAME

  YOUR-APP-NAME:
    image: registry.gitlab.joy-dev.com/YOUR-APP-NAME/backend:${IMAGE_TAG}
    container_name: YOUR-APP-NAME-api
    restart: always
    volumes:
      - ./log:/var/log
      - ./logs:/YOUR-APP-NAME/log
      - ./storage:/YOUR-APP-NAME/storage
      - ./assets:/YOUR-APP-NAME/public/assets
    ports:
      - '127.0.0.1:3000:3000'
    env_file: .env
    networks:
      - YOUR-APP-NAME

networks:
  YOUR-APP-NAME:
